version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
#      - run:
#          name: Test
#          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Deploy
          command: npm publish
